# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BazaltUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('auth', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('agentCode', models.CharField(max_length=15)),
            ],
        ),
    ]
