# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wienerberger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wienerbergeruser',
            name='auth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wienerbergeruser',
            name='date',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
